# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image:
  name: studiovisual/ci-php-node:latest
pipelines:
  branches:
    master:
      - step:
          caches:
            - node
            - composer
          script:
            - composer install --no-dev
            - composer dump -o
            - npm install
            - npm run dev
            - rsync --no-perms -O --exclude=node_modules/ --exclude=.git/ --exclude=.env --delete  -Prltvz ./ studio@intest.com.br:/mnt/intest-volume/misterprint/public/wp-content/plugins/misterprint-ecommerce
