<?php
return [
	'vc_mp_newsletter' => \MisterPrint\Components\Newsletter::class,
	'vc_mp_categories' => \MisterPrint\Components\Categories::class,
	'vc_mp_categories_featured' => \MisterPrint\Components\CategoriesFeatured::class,
	'vc_mp_category' => \MisterPrint\Components\Category::class,
	'vc_mp_category_configuration' => \MisterPrint\Components\CategoryConfiguration::class,
	'vc_mp_login' => \MisterPrint\Components\Login::class,
	'vc_mp_cart' => \MisterPrint\Components\Cart::class,
	'vc_mp_checkout_shipping' => \MisterPrint\Components\CheckoutShipping::class,
	'vc_mp_panel_addresses' => \MisterPrint\Components\PanelAddresses::class,
	'vc_mp_panel_data' => \MisterPrint\Components\PanelData::class,
	'vc_mp_panel_orders' => \MisterPrint\Components\PanelOrders::class,
	'vc_mp_graphic_production' => \MisterPrint\Components\GraphicProduction::class,
	'vc_mp_incomplete_register' => \MisterPrint\Components\IncompleteRegister::class,
	'vc_mp_register' => \MisterPrint\Components\Register::class,
	'vc_mp_checkout_complete' => \MisterPrint\Components\CheckoutComplete::class,
	'vc_mp_checkout_billing' => \MisterPrint\Components\CheckoutBilling::class,
	'vc_mp_checkout_e_rede_card' => \MisterPrint\Components\CheckoutERedeCard::class,
	'vc_mp_send_art' => \MisterPrint\Components\SendArt::class,
	'vc_mp_panel_conta_corrente' => \MisterPrint\Components\ContaCorrente::class,
	'vc_mp_lista_fretes' => \MisterPrint\Components\ListaFretes::class,
	'vc_mp_recovery_password' =>  \MisterPrint\Components\RecoveryPassword::class,
	'mp_balcony_art_creation' =>  \MisterPrint\Components\Balcony\ArtCreation::class,
	'mp_mega_menu' =>  \MisterPrint\Components\ProductsMegaMenu::class,
	'mp_mobile_mega_menu' =>  \MisterPrint\Components\ProductsMegaMenuMobile::class,
	'vc_mp_panel_favorites' =>  \MisterPrint\Components\PanelFavorites::class,
	'vc_mp_subcategories' =>  \MisterPrint\Components\Subcategories::class,
	'mp_coupon' =>  \MisterPrint\Components\Coupon::class,
	'mp_button' =>  \MisterPrint\Components\Button::class,
];
